//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Franpette.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Franpette.Resources.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About....
        /// </summary>
        internal static string aboutToolStripMenuItem {
            get {
                return ResourceManager.GetString("aboutToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        internal static string address_placeholder {
            get {
                return ResourceManager.GetString("address_placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string apply_button {
            get {
                return ResourceManager.GetString("apply_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applications.
        /// </summary>
        internal static string apps_groupbox {
            get {
                return ResourceManager.GetString("apps_groupbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic log in.
        /// </summary>
        internal static string autologin_checkBox {
            get {
                return ResourceManager.GetString("autologin_checkBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To log in automaticaly, check the box below..
        /// </summary>
        internal static string autologin_label {
            get {
                return ResourceManager.GetString("autologin_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel current operation.
        /// </summary>
        internal static string cancelToolStripMenuItem {
            get {
                return ResourceManager.GetString("cancelToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates....
        /// </summary>
        internal static string checkForUpdatesToolStripMenuItem {
            get {
                return ResourceManager.GetString("checkForUpdatesToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse....
        /// </summary>
        internal static string cld_button {
            get {
                return ResourceManager.GetString("cld_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your current destination directory is:.
        /// </summary>
        internal static string cld_label {
            get {
                return ResourceManager.GetString("cld_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear credentials....
        /// </summary>
        internal static string clearCredentialsToolStripMenuItem {
            get {
                return ResourceManager.GetString("clearCredentialsToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        internal static string disconnectToolStripMenuItem {
            get {
                return ResourceManager.GetString("disconnectToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string edit_menuItem {
            get {
                return ResourceManager.GetString("edit_menuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username/password.
        /// </summary>
        internal static string error_1 {
            get {
                return ResourceManager.GetString("error_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server is inaccessible.
        /// </summary>
        internal static string error_2 {
            get {
                return ResourceManager.GetString("error_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All fields are not filled.
        /// </summary>
        internal static string error_3 {
            get {
                return ResourceManager.GetString("error_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection failed.
        /// </summary>
        internal static string error_default {
            get {
                return ResourceManager.GetString("error_default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string exitToolStripMenuItem {
            get {
                return ResourceManager.GetString("exitToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string file_menuItem {
            get {
                return ResourceManager.GetString("file_menuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Franpette inspects your files....
        /// </summary>
        internal static string franpette_checkCsv {
            get {
                return ResourceManager.GetString("franpette_checkCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Franpette is ready..
        /// </summary>
        internal static string franpette_ready {
            get {
                return ResourceManager.GetString("franpette_ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?.
        /// </summary>
        internal static string help_menuItem {
            get {
                return ResourceManager.GetString("help_menuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you change the language, you need to restart Franpette..
        /// </summary>
        internal static string langInfo_label {
            get {
                return ResourceManager.GetString("langInfo_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select language:.
        /// </summary>
        internal static string langList_label {
            get {
                return ResourceManager.GetString("langList_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging in....
        /// </summary>
        internal static string logging_in {
            get {
                return ResourceManager.GetString("logging_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        internal static string login_button {
            get {
                return ResourceManager.GetString("login_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to message of the day.
        /// </summary>
        internal static string MOTD_label {
            get {
                return ResourceManager.GetString("MOTD_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string password_placeholder {
            get {
                return ResourceManager.GetString("password_placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string refreshToolStripMenuItem {
            get {
                return ResourceManager.GetString("refreshToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember.
        /// </summary>
        internal static string remember_checkBox {
            get {
                return ResourceManager.GetString("remember_checkBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report a bug....
        /// </summary>
        internal static string reportABugToolStripMenuItem {
            get {
                return ResourceManager.GetString("reportABugToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        internal static string server_menuItem {
            get {
                return ResourceManager.GetString("server_menuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings saved successfuly !.
        /// </summary>
        internal static string settings_saved {
            get {
                return ResourceManager.GetString("settings_saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string settings_window {
            get {
                return ResourceManager.GetString("settings_window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings....
        /// </summary>
        internal static string settingsToolStripMenuItem {
            get {
                return ResourceManager.GetString("settingsToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show files.
        /// </summary>
        internal static string showFilesToolStripMenuItem {
            get {
                return ResourceManager.GetString("showFilesToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select page:.
        /// </summary>
        internal static string tree_label {
            get {
                return ResourceManager.GetString("tree_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection.
        /// </summary>
        internal static string treeView_connection {
            get {
                return ResourceManager.GetString("treeView_connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directories.
        /// </summary>
        internal static string treeView_directories {
            get {
                return ResourceManager.GetString("treeView_directories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string treeView_language {
            get {
                return ResourceManager.GetString("treeView_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string username_placeholder {
            get {
                return ResourceManager.GetString("username_placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string view_menuItem {
            get {
                return ResourceManager.GetString("view_menuItem", resourceCulture);
            }
        }
    }
}
